# Generated by Django 3.0.3 on 2020-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_evnets'),
    ]

    operations = [
        migrations.AddField(
            model_name='mayor_and_councilor',
            name='mayor_or_councilor_image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
