# Generated by Django 3.0.3 on 2020-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_mayor_and_councilor_mayor_or_councilor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evnets',
            name='Ecent_location',
        ),
        migrations.RemoveField(
            model_name='evnets',
            name='Events_time',
        ),
        migrations.AddField(
            model_name='evnets',
            name='e_date',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='evnets',
            name='e_time',
            field=models.CharField(default='', max_length=150),
        ),
    ]
