# Generated by Django 3.0.3 on 2020-09-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_auto_20200910_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='evnets',
            name='Ecent_location',
            field=models.CharField(default='', max_length=150),
        ),
    ]
