# Generated by Django 3.0.3 on 2020-09-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_evnets_ecent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evnets',
            name='Events_images',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mayor_and_councilor',
            name='mayor_or_councilor_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
