# Generated by Django 3.0.3 on 2020-09-12 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_auto_20200911_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
