# Generated by Django 3.0.3 on 2020-09-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_news_news_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainer_name', models.CharField(default='', max_length=50)),
                ('complainer_email', models.CharField(default='', max_length=30)),
                ('compain_location', models.CharField(default='', max_length=100)),
                ('complain_subject', models.CharField(default='', max_length=100)),
                ('problem_details', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
