# Generated by Django 3.0.3 on 2020-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_complain_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain_details',
            name='problem_categories',
            field=models.CharField(choices=[('traffic', 'Traffic'), ('water', 'Water'), ('loadshaading', 'Load Shaading'), ('dirtyproblem', 'Dirty Problem'), ('airPolution', 'Air Polution')], default='water', max_length=20),
        ),
    ]
